version: '3.7'

# Define services
services:

  # Frontend Service 
  app-client:
    image: diptadas/acmsac-client
    build:
      context: app-client # build image from `app-client` directory
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: /api
    ports:
      - "80:80" # only open ports 80 and 443 to outside
      - "443:443"
    restart: always
    depends_on:
      - app-server
    volumes:
      - ./ssl:/etc/ssl
    networks:
      - app-internal

  # Backend service
  app-server:
    image: diptadas/acmsac-server
    build:
      context: app-server # build image from `app-server` directory
      dockerfile: Dockerfile
    expose:
      - "8080" # expose 8080 to internal network not outside
    restart: always
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/acmsacdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: acmsac
      SPRING_DATASOURCE_PASSWORD: acmsac#cloudhubs@baylor     
    networks:
      - app-internal  

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_DATABASE: acmsacdb
      MYSQL_USER: acmsac
      MYSQL_PASSWORD: acmsac#cloudhubs@baylor
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-internal  
  
volumes:
  db-data:

networks:
  app-internal:
