package com.example.polls.model;

import lombok.Data;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Data
@Entity
public class Paper {
    @Id
    // TODO: use paper ID instead of autogenerated ID
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // TODO: add other paper attributes

    // don't use Set, order matters
    @OneToMany
    List<Comment> comments = new ArrayList<>();
}
